name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go environment
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Prepare build environment
      run: mkdir -p builds

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build router
      run: go build -v -o ./builds/router ./cmd/router

    - name: Create archive tarball
      run: tar -zcf builds.tar.gz builds/
    
    - name: Archive artifacts
      uses: actions/upload-artifact@master
      with:
        name: builds.tar.gz
        path: builds.tar.gz
